"""empty message

Revision ID: 67c7aa88f90e
Revises: ab940590fd33
Create Date: 2019-12-30 16:02:00.633914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c7aa88f90e'
down_revision = 'ab940590fd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tag', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_tag', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.drop_column('post_tag', 'tag_id')
    # ### end Alembic commands ###
