"""empty message

Revision ID: b0bcf1a90a72
Revises: 1f822bdfd20e
Create Date: 2020-01-01 18:37:35.382157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0bcf1a90a72'
down_revision = '1f822bdfd20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='photo_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_pkey')
    )
    # ### end Alembic commands ###
